#! /usr/bin/env sh

echo "creating schema ${DB_NAME}"

PGPASSWORD=${ADMIN_PASSWORD} psql -d ${DB_NAME} -p ${PORT} -U${ADMIN_USER} -c "DROP SCHEMA IF EXISTS ${DB_NAME} CASCADE;"
PGPASSWORD=${ADMIN_PASSWORD} psql -d ${DB_NAME} -p ${PORT} -U${ADMIN_USER} -c "CREATE SCHEMA IF NOT EXISTS ${DB_NAME} AUTHORIZATION ${DB_USER};"
