#! /usr/bin/env sh

echo "creating role ${READWRITE_ROLE} in schema ${DB_NAME} and adding user ${DB_USER} to it"

# create a readwrite role
PGPASSWORD=${ADMIN_PASSWORD} psql -d ${DB_NAME} -p ${PORT} -U ${ADMIN_USER} -c "CREATE ROLE ${READWRITE_ROLE};"
PGPASSWORD=${ADMIN_PASSWORD} psql -d ${DB_NAME} -p ${PORT} -U ${ADMIN_USER} -c "GRANT CONNECT ON DATABASE ${DB_NAME} TO ${READWRITE_ROLE};"
PGPASSWORD=${ADMIN_PASSWORD} psql -d ${DB_NAME} -p ${PORT} -U ${ADMIN_USER} -c "GRANT USAGE, CREATE ON SCHEMA ${DB_NAME} TO ${READWRITE_ROLE};"
# grant privileges to existing tables in schema
PGPASSWORD=${ADMIN_PASSWORD} psql -d ${DB_NAME} -p ${PORT} -U ${ADMIN_USER} -c "GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA ${DB_NAME} TO ${READWRITE_ROLE};"
# grant privileges to future tables
PGPASSWORD=${ADMIN_PASSWORD} psql -d ${DB_NAME} -p ${PORT} -U ${ADMIN_USER} -c "ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${READWRITE_ROLE};"
PGPASSWORD=${ADMIN_PASSWORD} psql -d ${DB_NAME} -p ${PORT} -U ${ADMIN_USER} -c "GRANT USAGE ON ALL SEQUENCES IN SCHEMA ${DB_NAME} TO ${READWRITE_ROLE};"
PGPASSWORD=${ADMIN_PASSWORD} psql -d ${DB_NAME} -p ${PORT} -U ${ADMIN_USER} -c "ALTER DEFAULT PRIVILEGES IN SCHEMA ${DB_NAME} GRANT USAGE ON SEQUENCES TO ${READWRITE_ROLE};"
PGPASSWORD=${ADMIN_PASSWORD} psql -d ${DB_NAME} -p ${PORT} -U ${ADMIN_USER} -c "ALTER DEFAULT PRIVILEGES GRANT ALL ON FUNCTIONS TO ${READWRITE_ROLE};"

# add user to the readwrite role
PGPASSWORD=${ADMIN_PASSWORD} psql -d ${DB_NAME} -p ${PORT} -U ${ADMIN_USER} -c "GRANT ${READWRITE_ROLE} TO ${DB_USER};"